### ISSUE TITLE
Rework code to use SQLite database

### ISSUE THREAD

**Issue by edsondearaujo** [edsondearaujo/sales_automation#12]
# Descrição
Issue dedicada a refatoração do código para trabalhar com o banco de dados SQLite.

# Tarefas
- [x] fazer adaptação do arquivo database.py
- [x] adatar main.py para criar instância do banco de dados

# Critério de aceitação
- [x] a aplicação deve inserir dados no banco de dados sem afetar o funcionamento do sistema

**Comment by edsondearaujo** [comment]
O banco de dados está apresentando alguns erros. Estou trabalhando nisso.


```Menu:
1. Inserir Produto
2. Inserir Venda
3. Gerar Relatório
4. Sair
Escolha uma opção: 3
Nenhuma venda registrada.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ed/projeto_pessoal/sales_report_automation/src/main.py", line 48, in <module>
    main()
  File "/home/ed/projeto_pessoal/sales_report_automation/src/main.py", line 35, in main
    print(f"Total Geral: R$ {relatorio['total_geral']:.2f}")
                             ~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```
